version: '3'

services:
  ftp:
    build:
      context: .
      dockerfile: Dockerfile-ftp
      args:
        FTP_PORT: 8888
        USER: username
        PASSWORD: Qwerty123
    container_name: ftp
    ports:
      - 8080:8888
      - 30000-30009:30000-30009
    networks:
      - app_network
    hostname: ftp
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app
    networks:
      - app_network
    depends_on:
      - ftp
    hostname: app
    environment:
      USERNAME: username
      PASSWORD: Qwerty123
      FTP_PORT: 8888
      HOST: ftp

networks:
  app_network:
    driver: bridge
